# Generated by Django 5.2.17 on 2026-09-11 10:54

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(blank=True, max_length=13, verbose_name='Cedula')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{7,20}$', 'Ingrese un telefono valido (solo numeros, espacios, + - y parentesis).')], verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='entrenadores/', verbose_name='Fotografia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('dias', models.CharField(blank=True, max_length=20, verbose_name='Dias de entrenamiento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('valor_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor mensual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entrenadores', models.ManyToManyField(blank=True, related_name='categorias', to='jogabonito.entrenador', verbose_name='Entrenadores')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['hora_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(default='', max_length=100, unique=True, verbose_name='URL')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, verbose_name='Descripcion')),
                ('icono', models.CharField(default='fa-solid fa-layer-group', max_length=60, verbose_name='Icono')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GruposModulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Grupo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modulos', models.ManyToManyField(to='jogabonito.modulo', verbose_name='Modulos')),
            ],
            options={
                'verbose_name': 'Grupo de modulos',
                'verbose_name_plural': 'Grupos de modulos',
                'ordering': ['grupo'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('rol', models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'ENTRENADOR')], default=2, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{7,20}$', 'Ingrese un telefono valido (solo numeros, espacios, + - y parentesis).')], verbose_name='Telefono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
                'ordering': ['usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(blank=True, max_length=13, verbose_name='Cedula')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{7,20}$', 'Ingrese un telefono valido (solo numeros, espacios, + - y parentesis).')], verbose_name='Telefono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{7,20}$', 'Ingrese un telefono valido (solo numeros, espacios, + - y parentesis).')], verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico')),
                ('parentesco', models.IntegerField(choices=[(1, 'PADRE'), (2, 'MADRE'), (3, 'ABUELO/A'), (4, 'TIO/A'), (5, 'HERMANO/A'), (6, 'OTRO')], default=1, verbose_name='Parentesco')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Direccion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(blank=True, max_length=13, verbose_name='Cedula')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='jugadores/', verbose_name='Fotografia')),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{7,20}$', 'Ingrese un telefono valido (solo numeros, espacios, + - y parentesis).')], verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Direccion')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name='Fecha de ingreso')),
                ('valor_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar vacio para usar el valor de la categoria.', max_digits=8, null=True, verbose_name='Valor mensual personalizado')),
                ('observacion', models.TextField(blank=True, verbose_name='Observacion general')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (2, 'INACTIVO'), (3, 'RETIRADO')], default=1, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='jogabonito.categoria', verbose_name='Categoria')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='jogabonito.representante', verbose_name='Representante')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['apellidos', 'nombres'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cedula', ''), _negated=True), fields=('cedula',), name='jugador_cedula_unica')],
            },
        ),
    ]
