# Generated by Django 5.2.17 on 2026-09-11 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.IntegerField(choices=[(1, 'PRESENTE'), (2, 'FALTA'), (3, 'ATRASO'), (4, 'JUSTIFICADO')], default=1, verbose_name='Estado')),
                ('observacion', models.CharField(blank=True, max_length=250, verbose_name='Observacion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='jogabonito.categoria', verbose_name='Categoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='jogabonito.jugador', verbose_name='Jugador')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'jugador__apellidos'],
                'indexes': [models.Index(fields=['categoria', 'fecha'], name='jogabonito__categor_17aeb6_idx'), models.Index(fields=['jugador', 'fecha'], name='jogabonito__jugador_d0c866_idx')],
                'constraints': [models.UniqueConstraint(fields=('jugador', 'categoria', 'fecha'), name='asistencia_unica_por_jugador_fecha')],
            },
        ),
    ]
