# Generated by Django 5.2.17 on 2026-09-11 11:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0002_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del interesado')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{7,20}$', 'Ingrese un telefono valido (solo numeros, espacios, + - y parentesis).')], verbose_name='Telefono')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('estado', models.IntegerField(choices=[(1, 'NUEVA'), (2, 'CONTACTADO'), (3, 'INSCRITO'), (4, 'DESCARTADO')], default=1, verbose_name='Estado')),
                ('nota_interna', models.TextField(blank=True, verbose_name='Nota interna')),
                ('origen_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='jogabonito.categoria', verbose_name='Grupo de interes')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de inscripcion',
                'verbose_name_plural': 'Solicitudes de inscripcion',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', '-fecha_creacion'], name='jogabonito__estado_c76448_idx')],
            },
        ),
    ]
