# Generated by Django 5.2.17 on 2026-09-11 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0003_solicitudinscripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='dorsal',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dorsal'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='pie_habil',
            field=models.IntegerField(blank=True, choices=[(1, 'DERECHO'), (2, 'IZQUIERDO'), (3, 'AMBOS')], null=True, verbose_name='Pie habil'),
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Que se mide')),
                ('descripcion', models.CharField(blank=True, max_length=250, verbose_name='Como se toma la prueba')),
                ('area', models.IntegerField(choices=[(1, 'TECNICA'), (2, 'FISICA'), (3, 'TACTICA'), (4, 'ACTITUD')], default=1, verbose_name='Area')),
                ('tipo_medida', models.IntegerField(choices=[(1, 'ESCALA 1 A 10'), (2, 'NUMERO CON UNIDAD'), (3, 'TIEMPO EN SEGUNDOS')], default=1, verbose_name='Tipo de medida')),
                ('unidad', models.CharField(blank=True, help_text='Ejemplo: seg, m, reps, goles. Solo para medida con numero.', max_length=15, verbose_name='Unidad')),
                ('mejor_es', models.IntegerField(choices=[(1, 'MIENTRAS MAS ALTO, MEJOR'), (2, 'MIENTRAS MAS BAJO, MEJOR')], default=1, verbose_name='Sentido de la mejora')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor minimo aceptado')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor maximo aceptado')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['area', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(verbose_name='Fecha de la prueba')),
                ('titulo', models.CharField(help_text='Ejemplo: Prueba semanal 3, Control de mitad de temporada.', max_length=120, verbose_name='Titulo')),
                ('observacion', models.TextField(blank=True, verbose_name='Observacion')),
                ('cerrada', models.BooleanField(default=False, help_text='Una evaluacion cerrada ya no admite cambios.', verbose_name='Cerrada')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='jogabonito.categoria', verbose_name='Categoria')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indicadores', models.ManyToManyField(related_name='evaluaciones', to='jogabonito.indicador', verbose_name='Que se va a medir')),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha', 'categoria__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('abreviatura', models.CharField(blank=True, max_length=6, verbose_name='Abreviatura')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Posicion',
                'verbose_name_plural': 'Posiciones',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='jogabonito.posicion', verbose_name='Posicion que le gusta'),
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('observacion', models.CharField(blank=True, max_length=250, verbose_name='Observacion')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='jogabonito.evaluacion', verbose_name='Evaluacion')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='jogabonito.indicador', verbose_name='Indicador')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='jogabonito.jugador', verbose_name='Jugador')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicion',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['-evaluacion__fecha', 'jugador__apellidos'],
                'indexes': [models.Index(fields=['jugador', 'indicador'], name='jogabonito__jugador_009807_idx'), models.Index(fields=['evaluacion', 'jugador'], name='jogabonito__evaluac_db4212_idx')],
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'jugador', 'indicador'), name='medicion_unica_por_evaluacion')],
            },
        ),
    ]
