# Generated by Django 5.2.17 on 2026-09-11 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0004_jugador_dorsal_jugador_pie_habil_indicador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='edad_maxima',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dejar vacio si el grupo no tiene limite de edad.', null=True, verbose_name='Edad maxima'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='edad_minima',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dejar vacio si el grupo no tiene limite de edad.', null=True, verbose_name='Edad minima'),
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Tipo de evaluacion')),
                ('descripcion', models.CharField(blank=True, max_length=250, verbose_name='Para que sirve')),
                ('color', models.CharField(default='secondary', help_text='primary, success, danger, warning, info, secondary.', max_length=20, verbose_name='Color')),
                ('es_inicial', models.BooleanField(default=False, help_text='Marca la linea base del jugador: con que llego a la academia.', verbose_name='Es la prueba inicial')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de evaluacion',
                'verbose_name_plural': 'Tipos de evaluacion',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='jogabonito.tipoevaluacion', verbose_name='Tipo de evaluacion'),
        ),
    ]
