# Generated by Django 5.2.17 on 2026-09-11 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0005_categoria_edad_maxima_categoria_edad_minima_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Beca, hermano en la academia, convenio... Se aplica sobre el valor del mes.', max_digits=5, verbose_name='Descuento (%)'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='motivo_descuento',
            field=models.CharField(blank=True, max_length=120, verbose_name='Motivo del descuento'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='valor_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se llena, este jugador paga siempre este valor aunque suba el de la categoria.', max_digits=8, null=True, verbose_name='Precio congelado'),
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('mes', models.IntegerField(choices=[(1, 'ENERO'), (2, 'FEBRERO'), (3, 'MARZO'), (4, 'ABRIL'), (5, 'MAYO'), (6, 'JUNIO'), (7, 'JULIO'), (8, 'AGOSTO'), (9, 'SEPTIEMBRE'), (10, 'OCTUBRE'), (11, 'NOVIEMBRE'), (12, 'DICIEMBRE')], verbose_name='Mes')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Anio')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor a pagar')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento aplicado (%)')),
                ('fecha_vencimiento', models.DateField(verbose_name='Se vence el')),
                ('estado', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'PAGADO'), (3, 'EXONERADO')], default=1, verbose_name='Estado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('forma_pago', models.IntegerField(blank=True, choices=[(1, 'EFECTIVO'), (2, 'TRANSFERENCIA'), (3, 'OTRO')], null=True, verbose_name='Forma de pago')),
                ('comprobante', models.CharField(blank=True, max_length=60, verbose_name='Comprobante')),
                ('observacion', models.CharField(blank=True, max_length=250, verbose_name='Observacion')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='jogabonito.jugador', verbose_name='Jugador')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensualidad',
                'verbose_name_plural': 'Mensualidades',
                'ordering': ['-anio', '-mes', 'jugador__apellidos'],
                'indexes': [models.Index(fields=['anio', 'mes'], name='jogabonito__anio_772f05_idx'), models.Index(fields=['estado', 'fecha_vencimiento'], name='jogabonito__estado_dbca24_idx')],
                'constraints': [models.UniqueConstraint(fields=('jugador', 'mes', 'anio'), name='mensualidad_unica_por_mes')],
            },
        ),
    ]
