# Generated by Django 5.2.17 on 2026-09-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0006_jugador_descuento_jugador_motivo_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='peso_actitud',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cuanto pesa la actitud (0 a 3)'),
        ),
        migrations.AddField(
            model_name='posicion',
            name='peso_fisica',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cuanto pesa lo fisico (0 a 3)'),
        ),
        migrations.AddField(
            model_name='posicion',
            name='peso_tactica',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cuanto pesa la tactica (0 a 3)'),
        ),
        migrations.AddField(
            model_name='posicion',
            name='peso_tecnica',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cuanto pesa la tecnica (0 a 3)'),
        ),
    ]
