# Generated by Django 5.2.17 on 2026-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0007_posicion_peso_actitud_posicion_peso_fisica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='motivo_ajuste',
            field=models.CharField(blank=True, max_length=150, verbose_name='Motivo del ajuste'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='semanas_ausente',
            field=models.PositiveSmallIntegerField(default=0, help_text='De 0 a 4. Se le cobra solo las semanas que si entrena.', verbose_name='Semanas que avisó que no viene'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='valor_completo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lo que costaria el mes entero, antes de descontar semanas.', max_digits=8, verbose_name='Valor del mes completo'),
        ),
    ]
