# Generated by Django 5.2.17 on 2026-09-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0008_mensualidad_motivo_ajuste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensualidad',
            name='semanas_ausente',
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='dias_ausente',
            field=models.PositiveSmallIntegerField(default=0, help_text='Se le cobran solo los dias del periodo en que si puede entrenar.', verbose_name='Dias que avisó que no viene'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='periodo_fin',
            field=models.DateField(blank=True, null=True, verbose_name='y termina el'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='El periodo arranca el'),
        ),
    ]
