# Generated by Django 5.2.17 on 2026-09-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0009_remove_mensualidad_semanas_ausente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='valor_mensual',
        ),
    ]
