# Generated by Django 5.2.17 on 2026-09-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0010_remove_jugador_valor_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='cobro_activo',
            field=models.BooleanField(default=True, help_text='Mientras este prendido, al terminar un mes se le genera solo el siguiente. Apagalo si dejo de venir o si por ahora no se le cobra.', verbose_name='Cobrarle cada mes'),
        ),
    ]
