# Generated by Django 5.2.17 on 2026-09-11 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0011_cobro_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mensualidad',
            name='mensualidad_unica_por_mes',
        ),
        migrations.AddConstraint(
            model_name='mensualidad',
            constraint=models.UniqueConstraint(fields=('jugador', 'periodo_inicio'), name='mensualidad_unica_por_periodo'),
        ),
    ]
