# Generated by Django 5.2.17 on 2026-09-11 21:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0012_periodo_unico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='apodo',
            field=models.CharField(blank=True, help_text='El apodo con el que le gusta que le llamen. Sale en la lista y en la asistencia.', max_length=40, verbose_name='Como le dicen'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('tipo', models.IntegerField(choices=[(1, 'COMO VA'), (2, 'PARA FELICITARLO'), (3, 'HAY QUE ESTAR PENDIENTE'), (4, 'SALUD O LESION')], default=1, verbose_name='De que se trata')),
                ('texto', models.TextField(help_text='Que paso o que hay que trabajar con el.', verbose_name='La nota')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='jogabonito.entrenador', verbose_name='Quien la escribio')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='jogabonito.jugador', verbose_name='Jugador')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['jugador', '-fecha'], name='jogabonito__jugador_de757e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TurnoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('semana', models.DateField(verbose_name='Semana (lunes)')),
                ('nota', models.CharField(blank=True, max_length=200, verbose_name='Aviso de la semana')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='jogabonito.categoria', verbose_name='Grupo')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='jogabonito.entrenador', verbose_name='Le toca a')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno de la semana',
                'verbose_name_plural': 'Turnos de la semana',
                'ordering': ['-semana', 'categoria__hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'semana'), name='turno_unico_por_semana')],
            },
        ),
    ]
