# Generated by Django 5.2.17 on 2026-09-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0013_apodo_notas_turnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Solo si la prueba se toma en varios dias. Al que falto ese dia se le mide otro y queda con la fecha en que si vino.', null=True, verbose_name='Hasta'),
        ),
        migrations.AddField(
            model_name='medicion',
            name='fecha',
            field=models.DateField(blank=True, help_text='Si no se pone, vale el dia en que arranco la prueba.', null=True, verbose_name='Dia en que se le tomo'),
        ),
    ]
