# Generated by Django 5.2.17 on 2026-09-11 21:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0015_divisiones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='cuidados',
            field=models.TextField(blank=True, help_text='Asma, alergias, fascitis, una lesion vieja... Lo que el profe tiene que saber para no exigirle de mas. Sale marcado en su ficha y en la lista de asistencia.', verbose_name='Que hay que cuidarle'),
        ),
        migrations.CreateModel(
            name='ControlFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha del control')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('estatura', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Estatura (cm)')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observacion')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='jogabonito.jugador', verbose_name='Jugador')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control fisico',
                'verbose_name_plural': 'Controles fisicos',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('jugador', 'fecha'), name='control_unico_por_dia')],
            },
        ),
    ]
