# Generated by Django 5.2.17 on 2026-09-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0016_cuidados_y_control_fisico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoevaluacion',
            name='color',
            field=models.CharField(choices=[('primary', 'AZUL'), ('success', 'VERDE'), ('danger', 'ROJO'), ('warning', 'AMARILLO'), ('info', 'CELESTE'), ('secondary', 'GRIS'), ('dark', 'NEGRO')], default='secondary', help_text='Con este color sale la etiqueta del tipo en las listas.', max_length=20, verbose_name='Color'),
        ),
    ]
