# Generated by Django 5.2.17 on 2026-09-11 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0017_color_con_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='jugador',
            field=models.ForeignKey(blank=True, help_text='Dejalo vacio para tomarle la prueba a todo el grupo. Elige a uno cuando es una prueba individual: el que recien llega, o el que falto y hay que tomarle aparte.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_propias', to='jogabonito.jugador', verbose_name='Solo a este jugador'),
        ),
    ]
