# Generated by Django 5.2.17 on 2026-09-11 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0018_evaluacion_individual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reemplazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(verbose_name='Dia')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Por que')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reemplazos', to='jogabonito.categoria', verbose_name='Grupo')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazos', to='jogabonito.entrenador', verbose_name='Ese dia lo cubre')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reemplazo',
                'verbose_name_plural': 'Reemplazos',
                'ordering': ['-fecha', 'categoria__hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TurnoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('dia', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sabado'), ('7', 'Domingo')], max_length=1, verbose_name='Dia')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='jogabonito.categoria', verbose_name='Grupo')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='jogabonito.entrenador', verbose_name='Le toca a')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno del dia',
                'verbose_name_plural': 'Turnos por dia',
                'ordering': ['categoria__hora_inicio', 'dia'],
            },
        ),
        migrations.DeleteModel(
            name='TurnoSemanal',
        ),
        migrations.AddConstraint(
            model_name='reemplazo',
            constraint=models.UniqueConstraint(fields=('categoria', 'fecha'), name='reemplazo_unico_por_dia'),
        ),
        migrations.AddConstraint(
            model_name='turnodia',
            constraint=models.UniqueConstraint(fields=('categoria', 'dia'), name='turno_unico_por_dia'),
        ),
    ]
