# Generated by Django 5.2.17 on 2026-09-12 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0019_turnos_por_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnodia',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='turnodia',
            name='entrenador',
        ),
        migrations.RemoveField(
            model_name='turnodia',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='turnodia',
            name='usuario_modificacion',
        ),
        migrations.AddField(
            model_name='categoria',
            name='encargado',
            field=models.ForeignKey(blank=True, help_text='El que dirige este grupo. Se cambia cuando haga falta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_a_cargo', to='jogabonito.entrenador', verbose_name='Profe a cargo'),
        ),
        migrations.DeleteModel(
            name='Reemplazo',
        ),
        migrations.DeleteModel(
            name='TurnoDia',
        ),
    ]
