# Generated by Django 5.2.17 on 2026-09-13 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0020_encargado_del_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='apellido1',
            field=models.CharField(blank=True, max_length=60, verbose_name='Primer apellido'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='apellido2',
            field=models.CharField(blank=True, max_length=60, verbose_name='Segundo apellido'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='nombre1',
            field=models.CharField(blank=True, max_length=60, verbose_name='Primer nombre'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='nombre2',
            field=models.CharField(blank=True, max_length=60, verbose_name='Segundo nombre'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='apellido1',
            field=models.CharField(blank=True, max_length=60, verbose_name='Primer apellido'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='apellido2',
            field=models.CharField(blank=True, max_length=60, verbose_name='Segundo apellido'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='nombre1',
            field=models.CharField(blank=True, max_length=60, verbose_name='Primer nombre'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='nombre2',
            field=models.CharField(blank=True, max_length=60, verbose_name='Segundo nombre'),
        ),
        migrations.AddField(
            model_name='representante',
            name='apellido1',
            field=models.CharField(blank=True, max_length=60, verbose_name='Primer apellido'),
        ),
        migrations.AddField(
            model_name='representante',
            name='apellido2',
            field=models.CharField(blank=True, max_length=60, verbose_name='Segundo apellido'),
        ),
        migrations.AddField(
            model_name='representante',
            name='nombre1',
            field=models.CharField(blank=True, max_length=60, verbose_name='Primer nombre'),
        ),
        migrations.AddField(
            model_name='representante',
            name='nombre2',
            field=models.CharField(blank=True, max_length=60, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres'),
        ),
        migrations.AddConstraint(
            model_name='entrenador',
            constraint=models.UniqueConstraint(condition=models.Q(('cedula', ''), _negated=True), fields=('cedula',), name='entrenador_cedula_unica'),
        ),
        migrations.AddConstraint(
            model_name='representante',
            constraint=models.UniqueConstraint(condition=models.Q(('cedula', ''), _negated=True), fields=('cedula',), name='representante_cedula_unica'),
        ),
    ]
