# Generated by Django 5.2.17 on 2026-09-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0022_repartir_nombres_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='area',
            field=models.IntegerField(choices=[(1, 'TECNICA'), (2, 'FISICA'), (3, 'TACTICA'), (4, 'ACTITUD'), (5, 'PORTERO'), (6, 'MENTAL')], default=1, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='tipo_medida',
            field=models.IntegerField(choices=[(1, 'ESCALA 1 A 10'), (2, 'NUMERO CON UNIDAD'), (3, 'TIEMPO EN SEGUNDOS'), (4, 'PORCENTAJE (0 A 100)'), (5, 'SI O NO (1 O 0)')], default=1, verbose_name='Tipo de medida'),
        ),
    ]
