# Generated by Django 5.2.17 on 2026-09-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0023_areas_y_medidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='alergias',
            field=models.CharField(blank=True, help_text='A medicinas, comidas, picaduras. Vacio = ninguna conocida.', max_length=200, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='condicion_medica',
            field=models.TextField(blank=True, help_text='Lo que tiene: del corazon, asma, epilepsia, diabetes, condromalacia, fascitis plantar, una lesion vieja... Se anota al inscribirlo y se va actualizando.', verbose_name='Enfermedad o condicion'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='tipo_sangre',
            field=models.CharField(blank=True, help_text='Por si pasa algo en la cancha. Ejemplo: O+, A-.', max_length=5, verbose_name='Tipo de sangre'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='cuidados',
            field=models.TextField(blank=True, help_text='Lo que hay que cuidarle por esa condicion: nada de saltos, no doble jornada, que avise si le duele... Sale marcado en su ficha y en la lista de asistencia.', verbose_name='Que puede hacer y que no'),
        ),
    ]
