# Generated by Django 5.2.17 on 2026-09-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0024_salud_del_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='motivo_descuento',
            field=models.CharField(blank=True, help_text='El descuento puede ser de unos meses y despues no: por eso el motivo se guarda en el mes, no en la persona.', max_length=120, verbose_name='Por que el descuento'),
        ),
    ]
