# Generated by Django 5.2.17 on 2026-09-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogabonito', '0025_motivo_descuento_del_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Si el acuerdo fue "paga 5 menos" en vez de un porcentaje. Si pones los dos, manda este.', max_digits=8, verbose_name='Descuento (en dolares)'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Para cuando el acuerdo se hablo en plata: "este mes paga 5 menos".', max_digits=8, verbose_name='Descuento de este mes (en dolares)'),
        ),
    ]
